apiVersion: ctlptl.dev/v1alpha1
kind: Cluster
name: kind-kargo-dev-cluster
product: kind
registry: kargo-dev-registry
kindV1Alpha4Cluster:
  nodes:
  - extraPortMappings:
    - containerPort: 30081 # Orray API server
      hostPort: 30081
    - containerPort: 30082 # Orray API server proxy
      hostPort: 30082
