basePath: /api
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is the Orray API server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Orray API
  version: "1.0"
paths:
  /v1alpha1/canvases:
    get:
      description: List all the canvases the user has access to
      operationId: ListCanvasesV1alpha1
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: List all canvases
      tags:
      - Canvas
swagger: "2.0"
